"""add approved_at to trades

Revision ID: 00114c2303af
Revises: 80747618d09d
Create Date: 2026-04-21 21:52:57.839831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00114c2303af'
down_revision: Union[str, None] = '80747618d09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'approved_at')
    # ### end Alembic commands ###
