"""initial schema

Revision ID: 80747618d09d
Revises: 
Create Date: 2026-04-21 20:40:47.285422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80747618d09d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('forme_name', sa.String(), nullable=True),
    sa.Column('is_base_forme', sa.Boolean(), nullable=True),
    sa.Column('base_forme_id', sa.Integer(), nullable=True),
    sa.Column('is_mega', sa.Boolean(), nullable=True),
    sa.Column('is_regional_variant', sa.Boolean(), nullable=True),
    sa.Column('type1', sa.String(), nullable=False),
    sa.Column('type2', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('def', sa.Integer(), nullable=True),
    sa.Column('spatk', sa.Integer(), nullable=True),
    sa.Column('spdef', sa.Integer(), nullable=True),
    sa.Column('spe', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('sprite_url', sa.String(), nullable=True),
    sa.Column('artwork_url', sa.String(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('can_coexist_with', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['base_forme_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_species_id'), 'pokemon_species', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_species_pokedex_number'), 'pokemon_species', ['pokedex_number'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('draft_type', sa.String(), nullable=True),
    sa.Column('draft_timer_seconds', sa.Integer(), nullable=True),
    sa.Column('points_budget', sa.Integer(), nullable=True),
    sa.Column('roster_size', sa.Integer(), nullable=True),
    sa.Column('free_pick_slots', sa.Integer(), nullable=True),
    sa.Column('required_slots', sa.JSON(), nullable=True),
    sa.Column('series_format', sa.String(), nullable=True),
    sa.Column('match_format', sa.String(), nullable=True),
    sa.Column('playoff_format', sa.JSON(), nullable=True),
    sa.Column('keeper_enabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('roles', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('discord_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_webhooks_id'), 'discord_webhooks', ['id'], unique=False)
    op.create_table('league_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_config_id'), 'league_config', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('points_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_season_id'), 'teams', ['season_id'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_auto_calculated', sa.Boolean(), nullable=True),
    sa.Column('auto_calc_metric', sa.String(), nullable=True),
    sa.Column('recipient_team_id', sa.Integer(), nullable=True),
    sa.Column('recipient_notes', sa.String(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_index(op.f('ix_awards_season_id'), 'awards', ['season_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_pick_number', sa.Integer(), nullable=True),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('pick_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.create_table('h2h_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('team_a_match_wins', sa.Integer(), nullable=True),
    sa.Column('team_b_match_wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_h2h_records_id'), 'h2h_records', ['id'], unique=False)
    op.create_index(op.f('ix_h2h_records_season_id'), 'h2h_records', ['season_id'], unique=False)
    op.create_table('pokemon_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('games_brought', sa.Integer(), nullable=True),
    sa.Column('games_led', sa.Integer(), nullable=True),
    sa.Column('direct_kills', sa.Integer(), nullable=True),
    sa.Column('passive_kills', sa.Integer(), nullable=True),
    sa.Column('total_kills', sa.Integer(), nullable=True),
    sa.Column('direct_deaths', sa.Integer(), nullable=True),
    sa.Column('passive_deaths', sa.Integer(), nullable=True),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('kill_death_differential', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('acquired_via', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_season_stats_id'), 'pokemon_season_stats', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_season_stats_season_id'), 'pokemon_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_pokemon_season_stats_species_id'), 'pokemon_season_stats', ['species_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_season_id'), 'schedule', ['season_id'], unique=False)
    op.create_table('season_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('point_cost', sa.Integer(), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('drafted_by_team_id', sa.Integer(), nullable=True),
    sa.Column('draft_pick_number', sa.Integer(), nullable=True),
    sa.Column('acquired_via', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drafted_by_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_pokemon_id'), 'season_pokemon', ['id'], unique=False)
    op.create_index(op.f('ix_season_pokemon_season_id'), 'season_pokemon', ['season_id'], unique=False)
    op.create_index(op.f('ix_season_pokemon_species_id'), 'season_pokemon', ['species_id'], unique=False)
    op.create_table('season_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('champion', sa.Boolean(), nullable=True),
    sa.Column('runner_up', sa.Boolean(), nullable=True),
    sa.Column('playoff_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_results_id'), 'season_results', ['id'], unique=False)
    op.create_index(op.f('ix_season_results_season_id'), 'season_results', ['season_id'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('game_differential', sa.Integer(), nullable=True),
    sa.Column('match_wins', sa.Integer(), nullable=True),
    sa.Column('match_losses', sa.Integer(), nullable=True),
    sa.Column('match_draws', sa.Integer(), nullable=True),
    sa.Column('match_differential', sa.Integer(), nullable=True),
    sa.Column('direct_kills', sa.Integer(), nullable=True),
    sa.Column('passive_kills', sa.Integer(), nullable=True),
    sa.Column('total_kills', sa.Integer(), nullable=True),
    sa.Column('direct_deaths', sa.Integer(), nullable=True),
    sa.Column('passive_deaths', sa.Integer(), nullable=True),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('kill_death_differential', sa.Integer(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_season_stats_id'), 'team_season_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_season_stats_season_id'), 'team_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_season_stats_team_id'), 'team_season_stats', ['team_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_team_id', sa.Integer(), nullable=False),
    sa.Column('proposed_to_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_week', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_by_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['proposed_to_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_season_id'), 'trades', ['season_id'], unique=False)
    op.create_table('waiver_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('priority_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_order_id'), 'waiver_order', ['id'], unique=False)
    op.create_index(op.f('ix_waiver_order_season_id'), 'waiver_order', ['season_id'], unique=False)
    op.create_table('waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('add_species_id', sa.Integer(), nullable=False),
    sa.Column('drop_species_id', sa.Integer(), nullable=True),
    sa.Column('priority_at_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['add_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['drop_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waivers_id'), 'waivers', ['id'], unique=False)
    op.create_index(op.f('ix_waivers_season_id'), 'waivers', ['season_id'], unique=False)
    op.create_table('draft_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('pick_position', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_order_draft_id'), 'draft_order', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_order_id'), 'draft_order', ['id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['season_pokemon_id'], ['season_pokemon.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_draft_id'), 'draft_picks', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_id'), 'draft_picks', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_games_won', sa.Integer(), nullable=True),
    sa.Column('away_games_won', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_table('roster_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('move1', sa.String(), nullable=True),
    sa.Column('move2', sa.String(), nullable=True),
    sa.Column('move3', sa.String(), nullable=True),
    sa.Column('move4', sa.String(), nullable=True),
    sa.Column('tera_type', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_pokemon_id'], ['season_pokemon.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_pokemon_id'), 'roster_pokemon', ['id'], unique=False)
    op.create_index(op.f('ix_roster_pokemon_team_id'), 'roster_pokemon', ['team_id'], unique=False)
    op.create_table('trade_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=False),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('season_pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_pokemon_id'], ['season_pokemon.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_assets_id'), 'trade_assets', ['id'], unique=False)
    op.create_index(op.f('ix_trade_assets_trade_id'), 'trade_assets', ['trade_id'], unique=False)
    op.create_table('trade_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_votes_id'), 'trade_votes', ['id'], unique=False)
    op.create_index(op.f('ix_trade_votes_trade_id'), 'trade_votes', ['trade_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('loser_team_id', sa.Integer(), nullable=True),
    sa.Column('replay_url', sa.String(), nullable=True),
    sa.Column('replay_source', sa.String(), nullable=True),
    sa.Column('replay_parsed', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['loser_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_match_id'), 'games', ['match_id'], unique=False)
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('was_brought', sa.Boolean(), nullable=True),
    sa.Column('was_lead', sa.Boolean(), nullable=True),
    sa.Column('direct_kills', sa.Integer(), nullable=True),
    sa.Column('passive_kills', sa.Integer(), nullable=True),
    sa.Column('direct_deaths', sa.Integer(), nullable=True),
    sa.Column('passive_deaths', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_stats_game_id'), 'game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_stats_id'), 'game_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_stats_id'), table_name='game_stats')
    op.drop_index(op.f('ix_game_stats_game_id'), table_name='game_stats')
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_games_match_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_trade_votes_trade_id'), table_name='trade_votes')
    op.drop_index(op.f('ix_trade_votes_id'), table_name='trade_votes')
    op.drop_table('trade_votes')
    op.drop_index(op.f('ix_trade_assets_trade_id'), table_name='trade_assets')
    op.drop_index(op.f('ix_trade_assets_id'), table_name='trade_assets')
    op.drop_table('trade_assets')
    op.drop_index(op.f('ix_roster_pokemon_team_id'), table_name='roster_pokemon')
    op.drop_index(op.f('ix_roster_pokemon_id'), table_name='roster_pokemon')
    op.drop_table('roster_pokemon')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_draft_picks_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_draft_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_draft_order_id'), table_name='draft_order')
    op.drop_index(op.f('ix_draft_order_draft_id'), table_name='draft_order')
    op.drop_table('draft_order')
    op.drop_index(op.f('ix_waivers_season_id'), table_name='waivers')
    op.drop_index(op.f('ix_waivers_id'), table_name='waivers')
    op.drop_table('waivers')
    op.drop_index(op.f('ix_waiver_order_season_id'), table_name='waiver_order')
    op.drop_index(op.f('ix_waiver_order_id'), table_name='waiver_order')
    op.drop_table('waiver_order')
    op.drop_index(op.f('ix_trades_season_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_team_season_stats_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_season_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_id'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_season_results_season_id'), table_name='season_results')
    op.drop_index(op.f('ix_season_results_id'), table_name='season_results')
    op.drop_table('season_results')
    op.drop_index(op.f('ix_season_pokemon_species_id'), table_name='season_pokemon')
    op.drop_index(op.f('ix_season_pokemon_season_id'), table_name='season_pokemon')
    op.drop_index(op.f('ix_season_pokemon_id'), table_name='season_pokemon')
    op.drop_table('season_pokemon')
    op.drop_index(op.f('ix_schedule_season_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_pokemon_season_stats_species_id'), table_name='pokemon_season_stats')
    op.drop_index(op.f('ix_pokemon_season_stats_season_id'), table_name='pokemon_season_stats')
    op.drop_index(op.f('ix_pokemon_season_stats_id'), table_name='pokemon_season_stats')
    op.drop_table('pokemon_season_stats')
    op.drop_index(op.f('ix_h2h_records_season_id'), table_name='h2h_records')
    op.drop_index(op.f('ix_h2h_records_id'), table_name='h2h_records')
    op.drop_table('h2h_records')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_awards_season_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_teams_season_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_league_config_id'), table_name='league_config')
    op.drop_table('league_config')
    op.drop_index(op.f('ix_discord_webhooks_id'), table_name='discord_webhooks')
    op.drop_table('discord_webhooks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_pokemon_species_pokedex_number'), table_name='pokemon_species')
    op.drop_index(op.f('ix_pokemon_species_id'), table_name='pokemon_species')
    op.drop_table('pokemon_species')
    # ### end Alembic commands ###
